language: php

php:
  - 7.1

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v